### ISSUE TITLE
Sync should keep between() parameters into account

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/laravel-schedule-monitor#14]
ie:

```
$schedule->command('do:something')
    ->hourlyAt(5)
    ->between('7:00', '23:59')
    ->monitorName('custom name here')
    ->graceTimeInMinutes(10);
```

Creates a cron definition in Oh Dear that looks like this:

```
5 * * * *
```

The `between()` condition isn't being translated to the cron schedule.

**Comment by paulrrogers** [comment]
@freekmurze I've taken a crack at this with https://github.com/laravel/framework/pull/34649.

Is that helpful? Or were you thinking of adapting the expression entirely here with DI or an adapter?

**Comment by freekmurze** [comment]
@paulrrogers That is certainly helpful. If that PR, after review, would get merged, the functionality would just work in our package.

**Comment by freekmurze** [comment]
@paulrrogers Unfortunately your pull request was not accepted. I'd probably accept a PR request that adds support for `between` to our package. Make sure to include tests, certainly for edge cases and things like `23:00 - 01:00`

**Comment by paulrrogers** [comment]
@freekmurze since the PR for the Laravel framework was rejected I've tried adding the code to this package. Though it looks like an automatic service provider won't work. Instead there is a manual step I've outlined in https://github.com/spatie/laravel-schedule-monitor/pull/25.

Sadly I'm having trouble getting the test to integration pass. If you have any insight please let me know.

**Comment by freekmurze** [comment]
We'll continue this in #25
